### ISSUE TITLE
[BUG] Several Text Changes

### ISSUE THREAD

**Issue by Wesley257** [GTBitsOfGood/angels-among-us#153]
## Description

* Email template: This should not start with "Congratulations" to the admin. Idk why we are congratulating them lol.
* Onboarding slide: Slide 8: "Are you able to foster dogs that DO NOT do well with" -> this needs to be something positive/more straight forward for better UX
* "Use my Preferences" Button: "Use my Settings" or "Import from profile" or equivalent
* "Volunteer preferences" in the email template needs to say capabilities

**Comment by katsukixyz** [comment]
Email template one is resolved
