### ISSUE TITLE
[BUG] Onboarding: Multi Select Dropdowns Shouldn't Disappear After Click

### ISSUE THREAD

**Issue by Wesley257** [GTBitsOfGood/angels-among-us#154]
## Description

Onboarding slide 3 and 4, when you choose a breed in the multi select, the dropdown closes or collapses. This shouldn't be the case since it is a multi select and you can select a ton at once. See profile page for proper function.

**Comment by katsukixyz** [comment]
Unable to reproduce - could you take another look?
