### ISSUE TITLE
[PMT] Allow admins to rotate photos after uploading. (2 week ticket)

### ISSUE THREAD

**Issue by colin4554** [GTBitsOfGood/angels-among-us#314]
## Overview
Allow users to rotate the orientation of photos they upload of the pet.

### Details:
- Add rotate buttons to the [File preview component](https://github.com/GTBitsOfGood/angels-among-us/blob/staging/web/components/PostCreationModal/FileUpload/FilePreview.tsx) if the file is an image.
- Install [`react-easy-crop`](https://www.npmjs.com/package/react-easy-crop) for the rotating. 
- Look at [this example for help](https://codesandbox.io/p/sandbox/react-easy-crop-demo-with-cropped-output-q8q1mnr01w?file=%2Fsrc%2Findex.js%3A28%2C36). We want the user to rotate the image and then replace the original image in our array with the rotated one. Look at the `removeFile()` function for how the updating occurs. 
- We don't need any of the crop/zoom/other stuff, so if you find an easier way to rotate the image that also works

**Comment by cduffy8** [comment]
https://github.com/GTBitsOfGood/angels-among-us/pull/316
